import type { ElementType } from "react";
import { BarChart3, Binary, Brain, GitBranch, SquareStack } from "lucide-react";

import type { AlgoMeta, Category, GraphEdge, GraphNode } from "@/app/algorithms/types";

export const metas: AlgoMeta[] = [
  {
    id: "bubble",
    category: "Sorting",
    name: "Bubble Sort",
    icon: "sort",
    explanation: "Repeatedly compare adjacent elements and swap them when they are out of order.",
    application: "Useful for teaching adjacent comparisons and for tiny nearly sorted lists.",
    complexity: { best: "O(n)", average: "O(n^2)", worst: "O(n^2)", space: "O(1)" },
    concepts: ["Adjacent comparison", "Swap", "Pass", "Early stop"],
  },
  {
    id: "selection",
    category: "Sorting",
    name: "Selection Sort",
    icon: "sort",
    explanation: "Select the smallest remaining element and place it at the next sorted position.",
    application: "Good when swaps are expensive because it performs at most n swaps.",
    complexity: { best: "O(n^2)", average: "O(n^2)", worst: "O(n^2)", space: "O(1)" },
    concepts: ["Minimum scan", "Partition", "In-place sorting"],
  },
  {
    id: "insertion",
    category: "Sorting",
    name: "Insertion Sort",
    icon: "sort",
    explanation: "Build a sorted prefix by inserting each new element where it belongs.",
    application: "Fast for small arrays and nearly sorted data; often used inside hybrid sorts.",
    complexity: { best: "O(n)", average: "O(n^2)", worst: "O(n^2)", space: "O(1)" },
    concepts: ["Sorted prefix", "Shifting", "Stable sort"],
  },
  {
    id: "merge",
    category: "Sorting",
    name: "Merge Sort",
    icon: "sort",
    explanation: "Divide the array, sort each half, then merge sorted runs back together.",
    application: "Reliable stable sorting for linked lists, external sorting, and large datasets.",
    complexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)", space: "O(n)" },
    concepts: ["Divide and conquer", "Merge", "Stable sort"],
  },
  {
    id: "quick",
    category: "Sorting",
    name: "Quick Sort",
    icon: "sort",
    explanation: "Choose a pivot, partition around it, then recursively sort both sides.",
    application: "A practical high-performance in-place sort when pivots are chosen well.",
    complexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n^2)", space: "O(log n)" },
    concepts: ["Pivot", "Partition", "Recursion"],
  },
  {
    id: "heap",
    category: "Sorting",
    name: "Heap Sort",
    icon: "sort",
    explanation: "Build a max heap, repeatedly extract the root, and restore heap order.",
    application: "Useful for guaranteed O(n log n) sorting with constant extra space.",
    complexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)", space: "O(1)" },
    concepts: ["Heap property", "Sift down", "Extraction"],
  },
  {
    id: "linear",
    category: "Searching",
    name: "Linear Search",
    icon: "search",
    explanation: "Check each element from left to right until the target is found.",
    application: "Works on unsorted data and simple streams where no index structure exists.",
    complexity: { best: "O(1)", average: "O(n)", worst: "O(n)", space: "O(1)" },
    concepts: ["Sequential scan", "Target match", "Early return"],
  },
  {
    id: "binary",
    category: "Searching",
    name: "Binary Search",
    icon: "search",
    explanation: "On sorted data, repeatedly cut the search interval in half.",
    application: "Used in indexes, dictionaries, answer-space search, and lookup tables.",
    complexity: { best: "O(1)", average: "O(log n)", worst: "O(log n)", space: "O(1)" },
    concepts: ["Sorted input", "Midpoint", "Interval shrink"],
  },
  {
    id: "stack",
    category: "Data Structures",
    name: "Stack",
    icon: "structure",
    explanation: "A last-in-first-out structure where pushes and pops happen at the top.",
    application: "Used in undo history, parsing, recursion, browser history, and backtracking.",
    complexity: { best: "Push/pop O(1)", average: "Push/pop O(1)", worst: "Push/pop O(1)", space: "O(n)" },
    concepts: ["LIFO", "Top pointer", "Overflow/underflow"],
  },
  {
    id: "queue",
    category: "Data Structures",
    name: "Queue",
    icon: "structure",
    explanation: "A first-in-first-out structure with enqueue at rear and dequeue at front.",
    application: "Used in scheduling, buffering, BFS, and request processing.",
    complexity: { best: "O(1)", average: "O(1)", worst: "O(1)", space: "O(n)" },
    concepts: ["FIFO", "Front", "Rear"],
  },
  {
    id: "circularQueue",
    category: "Data Structures",
    name: "Circular Queue",
    icon: "structure",
    explanation: "A queue where front and rear wrap around a fixed-size array.",
    application: "Used in ring buffers, streaming audio, and bounded scheduling queues.",
    complexity: { best: "O(1)", average: "O(1)", worst: "O(1)", space: "O(n)" },
    concepts: ["Modulo index", "Wrap-around", "Fixed capacity"],
  },
  {
    id: "linkedList",
    category: "Data Structures",
    name: "Linked List",
    icon: "structure",
    explanation: "Nodes store values and links, so insertion can happen without shifting arrays.",
    application: "Useful for dynamic memory layouts, adjacency lists, and frequent insert/delete operations.",
    complexity: { best: "Insert head O(1)", average: "Search O(n)", worst: "Search O(n)", space: "O(n)" },
    concepts: ["Node", "Pointer", "Head", "Traversal"],
  },
  {
    id: "bst",
    category: "Data Structures",
    name: "Binary Search Tree",
    icon: "structure",
    explanation: "Each node keeps smaller values on the left and larger values on the right.",
    application: "Used for ordered maps, sets, range queries, and tree traversal practice.",
    complexity: { best: "O(log n)", average: "O(log n)", worst: "O(n)", space: "O(n)" },
    concepts: ["Ordering invariant", "Insert path", "Traversal"],
  },
  {
    id: "bfs",
    category: "Graph Algorithms",
    name: "Breadth-First Search",
    icon: "graph",
    explanation: "Visit nodes level by level using a queue.",
    application: "Shortest paths in unweighted graphs, web crawling, and social network degrees.",
    complexity: { best: "O(V + E)", average: "O(V + E)", worst: "O(V + E)", space: "O(V)" },
    concepts: ["Queue", "Visited set", "Layer order"],
  },
  {
    id: "dfs",
    category: "Graph Algorithms",
    name: "Depth-First Search",
    icon: "graph",
    explanation: "Explore deeply along a path before backtracking.",
    application: "Cycle detection, topological sorting, maze solving, and connected components.",
    complexity: { best: "O(V + E)", average: "O(V + E)", worst: "O(V + E)", space: "O(V)" },
    concepts: ["Stack", "Recursion", "Backtracking"],
  },
  {
    id: "dijkstra",
    category: "Graph Algorithms",
    name: "Dijkstra's Algorithm",
    icon: "graph",
    explanation: "Always expand the unsettled node with the smallest known distance.",
    application: "Routing, navigation, network optimization, and weighted shortest paths.",
    complexity: { best: "O((V + E) log V)", average: "O((V + E) log V)", worst: "O((V + E) log V)", space: "O(V)" },
    concepts: ["Relaxation", "Priority choice", "Shortest distance"],
  },
  {
    id: "prim",
    category: "Graph Algorithms",
    name: "Prim's Algorithm",
    icon: "graph",
    explanation: "Grow a minimum spanning tree by adding the cheapest edge to a new node.",
    application: "Network design, cabling, clustering, and infrastructure planning.",
    complexity: { best: "O(E log V)", average: "O(E log V)", worst: "O(E log V)", space: "O(V)" },
    concepts: ["Minimum spanning tree", "Cut property", "Greedy choice"],
  },
  {
    id: "hanoi",
    category: "Recursive Problems",
    name: "Tower of Hanoi",
    icon: "recursive",
    explanation: "Move disks between pegs by solving smaller subproblems recursively.",
    application: "Classic model for recursion, call stacks, and exponential growth.",
    complexity: { best: "O(2^n)", average: "O(2^n)", worst: "O(2^n)", space: "O(n)" },
    concepts: ["Base case", "Recursive case", "Call stack"],
  },
  {
    id: "fibonacci",
    category: "Recursive Problems",
    name: "Fibonacci",
    icon: "recursive",
    explanation: "Build each number from the two previous values.",
    application: "Introduces recursion, dynamic programming, memoization, and recurrence relations.",
    complexity: { best: "O(n)", average: "O(n)", worst: "O(n)", space: "O(1)" },
    concepts: ["Recurrence", "Memoization", "Overlapping subproblems"],
  },
  {
    id: "nQueens",
    category: "Recursive Problems",
    name: "N-Queens",
    icon: "recursive",
    explanation: "Place queens row by row while avoiding same columns and diagonals.",
    application: "Great for understanding backtracking and constraint satisfaction.",
    complexity: { best: "O(n!)", average: "O(n!)", worst: "O(n!)", space: "O(n)" },
    concepts: ["Backtracking", "Constraint check", "Search tree"],
  },
];

export const categoryIcons: Record<Category, ElementType> = {
  Sorting: BarChart3,
  Searching: Binary,
  "Data Structures": SquareStack,
  "Graph Algorithms": GitBranch,
  "Recursive Problems": Brain,
};

export const sampleGraphNodes: GraphNode[] = [
  { id: "A", x: 12, y: 42 },
  { id: "B", x: 34, y: 18 },
  { id: "C", x: 35, y: 68 },
  { id: "D", x: 58, y: 25 },
  { id: "E", x: 62, y: 73 },
  { id: "F", x: 84, y: 48 },
];

export const sampleGraphEdges: GraphEdge[] = [
  { from: "A", to: "B", weight: 4 },
  { from: "A", to: "C", weight: 2 },
  { from: "B", to: "D", weight: 5 },
  { from: "C", to: "D", weight: 1 },
  { from: "C", to: "E", weight: 7 },
  { from: "D", to: "F", weight: 3 },
  { from: "E", to: "F", weight: 2 },
];
